package entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;

/**
 * @author SUN KI
 * @time 2021/9/27 14:37
 * @Desc
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
public class lbpol {
    public String edorno;
    public String grpcontno;
    public String grppolno;
    public String contno;
    public String polno;
    public String proposalno;
    public String prtno;
    public String conttype;
    public String poltypeflag;
    public String mainpolno;
    public String masterpolno;
    public String kindcode;
    public String riskcode;
    public String riskversion;
    public String managecom;
    public String agentcom;
    public String agenttype;
    public String agentcode;
    public String agentgroup;
    public String agentcode1;
    public String salechnl;
    public String handler;
    public String insuredno;
    public String insuredname;
    public String insuredsex;
    public String insuredbirthday;
    public Integer insuredappage;
    public Integer insuredpeoples;
    public String occupationtype;
    public String appntno;
    public String appntname;
    public String cvalidate;
    public String signcom;
    public String signdate;
    public String signtime;
    public String firstpaydate;
    public String payenddate;
    public String paytodate;
    public String getstartdate;
    public String enddate;
    public String accienddate;
    public String getyearflag;
    public Integer getyear;
    public String payendyearflag;
    public Integer payendyear;
    public String insuyearflag;
    public Integer insuyear;
    public String acciyearflag;
    public Integer acciyear;
    public String getstarttype;
    public String specifyvalidate;
    public String paymode;
    public String paylocation;
    public Integer payintv;
    public Integer payyears;
    public Integer years;
    public BigDecimal managefeerate;
    public BigDecimal floatrate;
    public String premtoamnt;
    public BigDecimal mult;
    public BigDecimal standprem;
    public BigDecimal prem;
    public BigDecimal sumprem;
    public BigDecimal amnt;
    public BigDecimal riskamnt;
    public BigDecimal leavingmoney;
    public String endorsetimes;
    public String claimtimes;
    public String livetimes;
    public String renewcount;
    public String lastgetdate;
    public String lastloandate;
    public String lastregetdate;
    public String lastedordate;
    public String lastrevdate;
    public Integer rnewflag;
    public String stopflag;
    public String expiryflag;
    public String autopayflag;
    public String interestdifflag;
    public String subflag;
    public String bnfflag;
    public String healthcheckflag;
    public String impartflag;
    public String reinsureflag;
    public String agentpayflag;
    public String agentgetflag;
    public String livegetmode;
    public String deadgetmode;
    public String bonusgetmode;
    public String bonusman;
    public String deadflag;
    public String smokeflag;
    public String remark;
    public String approveflag;
    public String approvecode;
    public String approvedate;
    public String approvetime;
    public String uwflag;
    public String uwcode;
    public String uwdate;
    public String uwtime;
    public String polapplydate;
    public String appflag;
    public String polstate;
    public String standbyflag1;
    public String standbyflag2;
    public String standbyflag3;
    public String operator;
    public String makedate;
    public String maketime;
    public String modifydate;
    public String modifytime;
    public Integer waitperiod;
    public String payrulecode;
    public String ascriptionrulecode;
    public String salechnldetail;
    public String riskseqno;
    public BigDecimal copys;
    public BigDecimal comfeerate;
    public BigDecimal branchfeerate;
    public String proposalcontno;
    public String contplancode;
    public BigDecimal cessamnt;
    public String stateflag;
    public BigDecimal supplementaryprem;
    public String acctype;
    public String etl_dt;
    public String etl_tm;
    public String etl_fg;
    public String op_ts;
    public String current_ts;
}
