package com.pactera.yhl.entity;

import java.io.Serializable;

public class FactPrem implements KLEntity, Serializable {
    public String date_id;
    public String managecom;
    public String managename;
    public String provincecode;
    public String provincename;
    public String workarea;
    public String workname;
    public String salechannel;
    public String contno;
    public String prtno;
    public String holder_id;
    public String holder_name;
    public String holder_age;
    public String holder_sex;
    public String holder_address;
    public String holder_mobile;
    public String holder_telephone;
    public String main_insured_id;
    public String main_insured_name;
    public String main_insured_sex;
    public String main_insured_address;
    public String main_insured_mobile;
    public String main_insured_telephone;
    public String main_insured_apply_age;
    public String main_payintv;
    public String main_pay_period;
    public String main_period_type;
    public String main_insur_period;
    public String main_insur_period_type;
    public String contplancode;
    public String contplanname;
    public String contplan_payintv;
    public String product_code;
    public String product_name;
    public String product_payintv;
    public String new_prem;
    public String hesi_prem;
    public String amount;
    public String count;
    public String main_copy_nums;
    public String main_amount;
    public String paymode;
    public String paymode_type;
    public String paymode_date;
    public String callback_date;
    public String inpu_date;
    public String customget_date;
    public String get_date;
    public String apply_date_c;
    public String cvali_date_c;
    public String sign_date_c;
    public String edorvali_date;
    public String state_flagcode_c;
    public String state_flag_c;
    public String agent_group;
    public String group_name;
    public String agent_code;
    public String agent_name;
    public String agent_com;
    public String agentcom_name;
    public String bank_id;
    public String bank_name;
    public String bank_sname;
    public String handler;
    public String sale_way;
    public String self_flag;
    public String ischeck;
    public String old_agentcode;
    public String source_id;
    public String load_date;

}
